[datasets]
replogle_h1 = "/raid/kreid/v_cell/competition_support_set/{competition_train,k562_gwps,rpe1,jurkat,k562,hepg2}.h5"

[training]
replogle_h1 = "train"

[zeroshot]

[fewshot]
[fewshot."replogle_h1.competition_train"]
val = ["CHMP3", "AKT2", "SHPRH",]
test = ["TMSB4X", "KLF10"]
