[datasets]
replogle_h1 = "/raid/kreid/v_cell/competition_support_set/"

[training]
replogle_h1 = "train"

[zeroshot]

[fewshot]
[fewshot."replogle_h1.competition_train"]
val = ["CHMP3", "AKT2", "SHPRH"]
test = ["TMSB4X", "KLF10"]
