# This configuration is optimized for both PDS and DES.
# It uses a hybrid loss combining a geometric loss on embeddings (for PDS)
# and a Negative Binomial loss on gene counts (for DES).

name: state
kwargs:
  # --- PDS Optimization ---
  # Use the 'energy' distance (MMD-like) for the main geometric loss.
  # Your custom weighted geomloss will be used here.
  loss: "energy"
  main_loss_weight: 1.0  # Tune this to balance PDS vs. DES.

  # --- DES Optimization ---
  # Enable the Negative Binomial decoder to model gene counts.
  nb_decoder: true
  decoder_loss_weight: 1.0 # Tune this to balance DES vs. PDS.

  # --- General Model Settings ---
  # It's recommended to use a reasonably large model.
  # These are good starting points, similar to state_lg.
  cell_set_len: 512
  hidden_dim: 1488
  transformer_backbone_key: "llama"
  transformer_backbone_kwargs:
      max_position_embeddings: ${model.kwargs.cell_set_len}
      hidden_size: ${model.kwargs.hidden_dim}
      intermediate_size: 5952
      num_hidden_layers: 6
      num_attention_heads: 12
      num_key_value_heads: 12
