# Generic wandb configuration
# Users should customize these values for their own use
entity: daniel-mario-buchberger-berufsschule-f-r-elektro-veranst
project: state
local_wandb_dir: ./wandb_logs
tags: [eval] 
